"""修改message_id 增加对于role的表示

Revision ID: 034c85c286ba
Revises: a6133cf4b0a6
Create Date: 2023-04-25 00:39:34.677679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034c85c286ba'
down_revision = 'a6133cf4b0a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'message_id',
               existing_type=sa.VARCHAR(length=36),
               comment='用于识别的UUID,最后一位表示role:0-system 1-user 2-assistant',
               type=sa.VARCHAR(length=37),
               existing_comment='用于识别的UUID',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'message_id',
               existing_type=sa.VARCHAR(length=37),
               type=sa.VARCHAR(length=36),
               comment='用于识别的UUID',
               existing_comment='用于识别的UUID,最后一位表示role:0-system 1-user 2-assistant',
               existing_nullable=False)
    # ### end Alembic commands ###
