"""change_message_conv_id_type

Revision ID: 36a83d9deb6b
Revises: 826b820d9f50
Create Date: 2023-04-22 15:00:06.783100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a83d9deb6b'
down_revision = '826b820d9f50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    print("begin to alter!!!")
    op.drop_constraint('message_conv_id_fkey', 'message', type_='foreignkey')
    op.alter_column('message', 'conv_id',
               existing_type=sa.INTEGER(),
               type_ = sa.String(),
               comment='对应的对话UUID',
               existing_comment='对应的对话ID',
               existing_nullable=True)
    print("test henley")
    op.create_foreign_key(None, 'message', 'conversation', ['conv_id'], ['conversation_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_conv_id_fkey', 'message', 'conversation', ['conv_id'], ['id'])
    op.alter_column('message', 'conv_id',
               existing_type=sa.INTEGER(),
               comment='对应的对话ID',
               existing_comment='对应的对话UUID',
               existing_nullable=True)
    # ### end Alembic commands ###
