"""add_datatime_on_message

Revision ID: 826b820d9f50
Revises: 9ae7647dc763
Create Date: 2023-04-19 01:51:06.624848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826b820d9f50'
down_revision = '9ae7647dc763'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('create_time', sa.DateTime(), nullable=True, comment='消息发送时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'create_time')
    # ### end Alembic commands ###
