"""create message

Revision ID: 9ae7647dc763
Revises: ad1ea6f4deec
Create Date: 2023-04-18 01:13:21.792061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae7647dc763'
down_revision = 'ad1ea6f4deec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='对应的用户ID'),
    sa.Column('conv_id', sa.Integer(), nullable=True, comment='对应的对话ID'),
    sa.Column('role', sa.Enum('system', 'user', 'assistant', name='role'), nullable=True, comment='对话对应的角色'),
    sa.Column('text', sa.String(), nullable=True, comment='发送的信息'),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conv_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
