"""修改message_id, 用于前端显示和识别

Revision ID: a6133cf4b0a6
Revises: 36a83d9deb6b
Create Date: 2023-04-25 00:33:10.160700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6133cf4b0a6'
down_revision = '36a83d9deb6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message_id', sa.String(length=37), nullable=False, comment='用于识别的UUID'))
    op.create_index(op.f('ix_message_message_id'), 'message', ['message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_message_id'), table_name='message')
    op.drop_column('message', 'message_id')
    # ### end Alembic commands ###
